---
title: "Mammographic dataset results"
author: "DSLAB"
format: html
editor: visual
---

```{r}
source('../GeneralAndMethodFunctions.R')

library(plyr)
library(dplyr)
library(ggplot2)
library(readr)
library(tidyr)
library(caret)
library(e1071)
library(CORElearn)
```

```{r}
df <- read_csv("../datasets/mammographic_masses.data", col_names = FALSE)

colnames(df) <- c("BI-RADS", "Age", "Shape", "Margin", "Density", "class")
df=df %>% mutate_if(is.character, as.numeric)

df = drop_na(df)
df$class <- as.factor(df$class)
str(df)
df[,-6] <- scale(df[,-6])

set.seed(1)
trainIndex <- createDataPartition(df$class,
                                  p = 0.7, # training contains 70% of data
                                  list = FALSE)
dfTrain <- df[ trainIndex,]
dfTest  <- df[-trainIndex,]
dim(dfTrain)



### Best parameters SVM
set.seed(1)
svm_cv <- tune("svm", class ~ ., data = dfTrain,
               kernel = 'radial', scale=FALSE,
               ranges = list(cost = c(0.001, 0.01, 0.1, 1, 5, 10, 20, 50, 100,
                                      150, 200)))
summary(svm_cv)
best_cost=svm_cv$best.model$cost


set.seed(1)
df_test_no_target <- dfTest[, setdiff(names(df), "class")]
df_train_no_target <- dfTrain[, setdiff(names(df), "class")]
set.seed(1)
model_svm_mammo = svm(class ~ ., data=dfTrain, kernel="radial", scale=FALSE, probability=TRUE, type="C", cost=best_cost)
pred_svm_train = predict(model_svm_mammo, df_train_no_target, probability=TRUE, decision.values = TRUE)
probs_model_train <- attr(pred_svm_train,"probabilities")
probs_model_train <- probs_model_train[,c("0", "1")]
probs_model_train_class1 <- probs_model_train[,'1']

# test
pred_svm_test = predict(model_svm_mammo, df_test_no_target, probability=TRUE, decision.values = TRUE)
probs_model_test <- attr(pred_svm_test,"probabilities")
probs_model_test <- probs_model_test[,c("0", "1")]
probs_model_test_class1 <- probs_model_test[,'1']

```

# Fixed thresholds: 1/2, 1/3-2/3, 1/4-2/4-3/4

## Classic cut: 1/2

```{r warning=FALSE, message=FALSE}
ths = c(1/2)
GPS_p_values = c('p_11','p12','r1_1','r21')
results_binary_train <- Case_FixedThreshold(dfTrain, probs_model_train_class1, ths, GPS_p_values)
print(results_binary_train)
```

```{r warning=FALSE, message=FALSE}
list_names_obs <- c('Benign','Malignant')
list_names_pred <- c('Low','High')
graph_train_bin <- barplot_CM(results_binary_train$CM,list_names_obs,list_names_pred)
graph_train_bin
#ggsave("Mammo_2x2_train.png", plot = graph_train_bin, width = 6, height = 4, dpi = 300)

```

In the test set:

```{r warning=FALSE, message=FALSE}
ths = c(1/2)
GPS_p_values = c('p_11','p12','r1_1','r21')
results_binary_test <- Case_FixedThreshold(dfTest, probs_model_test_class1, ths, GPS_p_values)
print(results_binary_test)
```

```{r warning=FALSE, message=FALSE}
list_names_obs <- c('Benign','Malignant')
list_names_pred <- c('Low','High')
graph_test_bin <- barplot_CM(results_binary_test$CM,list_names_obs,list_names_pred)
graph_test_bin
#ggsave("Mammo_2x2_test.png", plot = graph_test_bin, width = 6, height = 4, dpi = 300)

```

## 3 cuts: 1/4-2/4-3/4

```{r warning=FALSE, message=FALSE}
ths = c(1/4,2/4,3/4)
GPS_p_values = c('p_11','p14','r1_1','r41')
results_four_train <- Case_FixedThreshold(dfTrain, probs_model_train_class1, ths, GPS_p_values)
print(results_four_train)
```

```{r warning=FALSE, message=FALSE}
list_names_obs <- c('Benign','Malignant')
list_names_pred <- c('Low','Medium','High','Very high')
graph_train_four <- barplot_CM(results_four_train$CM,list_names_obs,list_names_pred)
graph_train_four
#ggsave("Mammo_4x2_train.png", plot = graph_train_four, width = 6, height = 4, dpi = 300)

```

In the test set:

```{r warning=FALSE, message=FALSE}
ths = c(1/4,2/4,3/4)
GPS_p_values = c('p_11','p14','r1_1','r41')
results_four_test <- Case_FixedThreshold(dfTest, probs_model_test_class1, ths, GPS_p_values)
print(results_four_test)
```

```{r warning=FALSE, message=FALSE}
list_names_obs <- c('Benign','Malignant')
list_names_pred <- c('Low','Medium','High','Very high')
graph_test_four <- barplot_CM(results_four_test$CM,list_names_obs,list_names_pred)
graph_test_four
#ggsave("Mammo_4x2_test.png", plot = graph_test_four, width = 6, height = 4, dpi = 300)

```

# Max GPS without constraints

## Max GPS(p14, p_11, r1_1)

```{r warning=FALSE, message=FALSE}
restriction = FALSE
num_cuts = 3
vector_GPS = c( 'p_11','p14', 'r1_1')
user_condition <- NULL
results_3cuts_MaxGPS_train <- AfterTheModel(dfTrain, probs_model_train,restriction,user_condition,vector_GPS,num_cuts)
print(results_3cuts_MaxGPS_train)
ths_for_test <- results_3cuts_MaxGPS_train$thresholds


```

```{r}

list_names_obs <- c('Low','High')
list_names_pred <- c('Low','Medium','High','Very high')
graph_3cuts_MaxGPS_train <- barplot_CM(results_3cuts_MaxGPS_train$best_CM,list_names_obs,list_names_pred)
graph_3cuts_MaxGPS_train
#ggsave("Mammo_MaxGPS_NoRestrictions_train.png", plot = graph_3cuts_MaxGPS_train, width = 6, height = 4, dpi = 300)

```

```{r}

probs_test_class1 <- probs_model_test[,'1'] 
thresholds <- sort(ths_for_test, decreasing=TRUE)
breaks <- c(Inf, thresholds, -Inf)
Y_pred_class_test <- cut(probs_test_class1, breaks = breaks, labels = 0:length(thresholds), right = FALSE)

CM_test <- table(Class_predicted = Y_pred_class_test,Class_observed = dfTest$class)
print(CM_test)

vector_GPS = c( 'p_11','p14', 'r1_1')
gps_test <- GPS_from_CM(CM_test,vector_GPS)
print(gps_test)



```

```{r}
graph_3cuts_MaxGPS_test <- barplot_CM(CM_test,list_names_obs,list_names_pred)
graph_3cuts_MaxGPS_test
#ggsave("Mammo_MaxGPS_NoRestrictions_test.png", plot = graph_3cuts_MaxGPS_test, width = 6, height = 4, dpi = 300)

```

# Calibration: isotonic

```{r}

class_train <- dfTrain$class
class_test <- dfTest$class

probs_train <- probs_model_train
probs_test <- probs_model_test

class_prin <- 2
calibration_model <- calibrate(class_train, probs_train[,class_prin], class1=class_prin, 
                               method="isoReg",assumeProbabilities=TRUE)

# apply the calibration to the testing set
calibratedProbs_train <- applyCalibration(probs_train[,class_prin], calibration_model)
calibratedProbs <- applyCalibration(probs_test[,class_prin], calibration_model)

ths = c(1/4,2/4,3/4)
GPS_p_values = c('p_11','p14','r1_1','r41')
results_iso <- Case_FixedThreshold(dfTest, calibratedProbs, ths, GPS_p_values)
results_iso
results_iso_train <- Case_FixedThreshold(dfTrain, calibratedProbs_train, ths, GPS_p_values)

```

```{r message=FALSE}
list_names_obs <- c('Low','High')
list_names_pred <- c('Low','Medium','High','Very high')
graph_bar_plot_iso <- barplot_CM(results_iso$CM,list_names_obs,list_names_pred)
graph_bar_plot_iso
#ggsave("Mammo_MaxGPS_IsoReg_test.png", plot = graph_bar_plot_iso, width = 6, height = 4, dpi = 300)
```

```{r message=FALSE}
list_names_obs <- c('Low','High')
list_names_pred <- c('Low','Medium','High','Very high')
graph_bar_plot_iso_train <- barplot_CM(results_iso_train$CM,list_names_obs,list_names_pred)
graph_bar_plot_iso_train
#ggsave("Mammo_MaxGPS_IsoReg_train.png", plot = graph_bar_plot_iso_train, width = 6, height = 4, dpi = 300)
```

# Case 4x2

## Max GPS with restrictions: case 4x2

```{r warning=FALSE, message=FALSE}
restriction = TRUE
user_condition <- function(p, p_, r, r_) {
  (r_[1] > 0.5) & (r_[2] > 0.1)   & (p[3]>0.7) & (p[3]<0.85) & (p[4]>0.85) & (p_[1]>0.8)
}

num_cuts = 3
vector_GPS = c('p14', 'p_11', 'r1_1') 
results_restric_four_train <- AfterTheModel(dfTrain, probs_model_train,restriction,user_condition,vector_GPS,num_cuts)
print(results_restric_four_train)
ths_for_test <- results_restric_four_train$thresholds
```

```{r warning=FALSE, message=FALSE}
list_names_obs <- c('Low','High')
list_names_pred <- c('Low','Medium','High','Very high')
graph_restric_four_train <- barplot_CM(results_restric_four_train$best_CM,list_names_obs,list_names_pred)
graph_restric_four_train
#ggsave("Mammo_MaxGPS_Restrictions_four_train.png", plot = graph_restric_four_train, width = 6, height = 4, dpi = 300)

```

```{r}
probs_test_class1 <- probs_model_test[,'1'] 
thresholds <- sort(ths_for_test, decreasing=TRUE)
breaks <- c(Inf, thresholds, -Inf)
Y_pred_class_test <- cut(probs_test_class1, breaks = breaks, labels = 0:length(thresholds), right = FALSE)

CM_test <- table(Class_predicted = Y_pred_class_test,Class_observed = dfTest$class)
print(CM_test)

vector_GPS = c('p14', 'p_11', 'r1_1')
gps_test <- GPS_from_CM(CM_test,vector_GPS)
print(gps_test)

```

```{r}
graph_restric_four_test <- barplot_CM(CM_test,list_names_obs,list_names_pred)
graph_restric_four_test
#ggsave("Mammo_MaxGPS_Restrictions_four_test.png", plot = graph_restric_four_test, width = 6, height = 4, dpi = 300)

```

## In the model Case 4x2

```{r}
user_condition <- function(p, p_, r, r_) {
  conditions <- list(
   list(value = r_[1], threshold = 0.5, op = ">"), 
   list(value = p_[1], threshold = 0.8, op = ">"), 
   list(value = r_[2], threshold = 0.1, op = ">"),   
    list(value = p[3], threshold = 0.7, op = ">"),    
    list(value = p[2], threshold = 0.85, op = "<"),   
   list(value = p[4], threshold = 0.85, op = ">")   
  )
  
  results <- lapply(conditions, function(cond) {
    if (cond$op == "<") return(cond$value < cond$threshold)
    if (cond$op == ">") return(cond$value > cond$threshold)
    if (cond$op == "<=") return(cond$value <= cond$threshold)
    if (cond$op == ">=") return(cond$value >= cond$threshold)
  })
  
  all_true = all(unlist(results))
  if (all_true){
    total_cond = TRUE
  } else{
    total_cond = FALSE
  }
  
  return(list(conditions = conditions, results = results,total_cond=total_cond))
}
```

```{r}
kernelSVM = 'radial'
num_cuts = 3
vector_GPS = c('p14', 'p_11', 'r1_1') 
cv_folds = 3
restriction = TRUE

results_In_train_four <- InTheModel(dfTrain,kernelSVM,num_cuts,cv_folds,vector_GPS,restriction,user_condition)
results_In_train_four

```

```{r}
model_in <- results_In_train_four$best_model_trained
probs_train_in <- predict(model_in,df_train_no_target, probability=TRUE, decision.values = TRUE)
probs_test_in <- predict(model_in,df_test_no_target, probability=TRUE, decision.values = TRUE)

probs_model_train_in <- attr(probs_test_in,"probabilities")
probs_model_train_in <- probs_model_train_in[,c("0", "1")]
probs_model_train_class1_in <- probs_model_train_in[,2]

probs_model_test_in <- attr(probs_test_in,"probabilities")
probs_model_test_in <- probs_model_test_in[,c("0", "1")]
probs_model_test_class1_in <- probs_model_test_in[,2]
```

```{r}
# Test
ths_in = results_In_train_four$thresholds
breaks <- c(Inf, ths_in, -Inf)
Y_pred_class <- cut(probs_model_test_class1_in, breaks = breaks, labels = 0:length(ths_in), right = FALSE)
unique_values <- unique(Y_pred_class) 
Y_pred_class <- factor(Y_pred_class, levels = sort(unique_values))
CM <- table(Class_predicted = Y_pred_class,Class_observed = dfTest$class)
CM
vector_GPS = c('p14', 'p_11', 'r1_1') 
GPS_from_CM(CM,vector_GPS)
```

```{r warning=FALSE, message=FALSE}
list_names_obs <- c('Low','High')
list_names_pred <- c('Low','Medium','High','Very high')
graph_in_four <- barplot_CM(CM,list_names_obs,list_names_pred)
graph_in_four
#ggsave("Mammo_InTheModel_test_four.png", plot = graph_in_four, width = 6, height = 4, dpi = 300)

```

```{r warning=FALSE, message=FALSE}
list_names_obs <- c('Low','High')
list_names_pred <- c('Low','Medium','High','Very high')
graph_in_four_testCV <- barplot_CM(results_In_train_four$best_CM_test,list_names_obs,list_names_pred)
graph_in_four_testCV
#ggsave("Mammo_InTheModel_test_four_CV.png", plot = graph_in_four_testCV, width = 6, height = 4, dpi = 300)

```
